name: 'Github Org Slack Summary'
description: 'Produces Github organization summaries and posts it on your fave Slack channel'
inputs:
  org:
    description: 'Org to report on'
    required: true
  github-token:
    description: 'Github access token'
    required: true
  slack-token:
    description: 'Access token with permissions to post on your desired Slack channel'
    required: true
  slack-channel:
    description: 'Channel the updates will be posted to'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
